// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SneakerStoree.DBContexts;

namespace SneakerStoree.Migrations
{
    [DbContext(typeof(SneakerStoreDBContex))]
    [Migration("20210731014938_CreateDBSneaker")]
    partial class CreateDBSneaker
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SneakerStoree.Entities.Sneaker", b =>
                {
                    b.Property<int>("SneakerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Information")
                        .IsRequired()
                        .HasColumnType("nvarchar(3000)")
                        .HasMaxLength(3000);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Photo")
                        .IsRequired()
                        .HasColumnType("nvarchar(300)")
                        .HasMaxLength(300);

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<int>("PublishYear")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("Size")
                        .HasColumnType("int");

                    b.Property<string>("SneakerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(500)")
                        .HasMaxLength(500);

                    b.Property<int>("TradeMarkId")
                        .HasColumnType("int");

                    b.HasKey("SneakerId");

                    b.HasIndex("TradeMarkId");

                    b.ToTable("Sneakers");

                    b.HasData(
                        new
                        {
                            SneakerId = 1,
                            Information = "Giày Đẹp",
                            IsDeleted = false,
                            Photo = "images/vans_b-w.jpg",
                            Price = 1350000,
                            PublishYear = 2019,
                            Quantity = 10,
                            Size = 42,
                            SneakerName = "Vans Old Skool Black White",
                            TradeMarkId = 4
                        },
                        new
                        {
                            SneakerId = 2,
                            Information = "Giày Đẹp",
                            IsDeleted = false,
                            Photo = "images/converse-w.jpg",
                            Price = 715000,
                            PublishYear = 2019,
                            Quantity = 10,
                            Size = 42,
                            SneakerName = "Converse 1970s Chuck Taylor 2",
                            TradeMarkId = 1
                        });
                });

            modelBuilder.Entity("SneakerStoree.Entities.TradeMark", b =>
                {
                    b.Property<int>("TradeMarkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TradeMarkName")
                        .IsRequired()
                        .HasColumnType("nvarchar(250)")
                        .HasMaxLength(250);

                    b.HasKey("TradeMarkId");

                    b.ToTable("TradeMarks");

                    b.HasData(
                        new
                        {
                            TradeMarkId = 1,
                            IsDeleted = false,
                            TradeMarkName = "Converse"
                        },
                        new
                        {
                            TradeMarkId = 2,
                            IsDeleted = false,
                            TradeMarkName = "Nike"
                        },
                        new
                        {
                            TradeMarkId = 3,
                            IsDeleted = false,
                            TradeMarkName = "Adidas"
                        },
                        new
                        {
                            TradeMarkId = 4,
                            IsDeleted = false,
                            TradeMarkName = "Vans"
                        });
                });

            modelBuilder.Entity("SneakerStoree.Entities.Sneaker", b =>
                {
                    b.HasOne("SneakerStoree.Entities.TradeMark", "TradeMarks")
                        .WithMany("Sneakers")
                        .HasForeignKey("TradeMarkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
